title: Beyza Nalbantoğlu
theme: jekyll-theme-minimal
#logo: /assets/logo.png  
#show_dowloands:true

# Sayfa başlığı ve açıklamalar gibi ek ayarlar
description: "Bu site projeler ve yazılım konularını içerir."
